import { execFile } from "node:child_process";
import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { promisify } from "node:util";

const execFileAsync = promisify(execFile);
const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(scriptDir, "..");
const outputPath = path.join(repoRoot, "src", "buildMeta.ts");

type GitMeta = {
  commitHash: string;
  shortHash: string;
  committedAtIso: string;
  commitCount: number;
};

const gitMeta = await readLatestGitCommitMeta();
const nextContent = buildMetaModuleSource(gitMeta);
const previousContent = await readTextFile(outputPath);

if (previousContent !== nextContent) {
  await writeFile(outputPath, nextContent, "utf8");
  console.log(`Updated ${path.relative(repoRoot, outputPath)}`);
} else {
  console.log(`No change in ${path.relative(repoRoot, outputPath)}`);
}

async function readLatestGitCommitMeta(): Promise<GitMeta> {
  try {
    const [{ stdout: metaStdout }, { stdout: countStdout }] = await Promise.all([
      execFileAsync(
        "git",
        ["log", "-1", "--format=%H%n%h%n%cI"],
        { cwd: repoRoot },
      ),
      execFileAsync("git", ["rev-list", "--count", "HEAD"], { cwd: repoRoot }),
    ]);
    const [fullHash = "", shortHash = "", committedAtIso = ""] =
      metaStdout.trim().split(/\r?\n/);
    return {
      commitHash: normalizeText(fullHash),
      shortHash: normalizeText(shortHash),
      committedAtIso: normalizeText(committedAtIso),
      commitCount: normalizeCommitCount(countStdout),
    };
  } catch {
    return {
      commitHash: "",
      shortHash: "",
      committedAtIso: "",
      commitCount: 0,
    };
  }
}

function buildMetaModuleSource(meta: Partial<GitMeta>): string {
  const payload = {
    commitHash: normalizeText(meta?.commitHash),
    shortHash: normalizeText(meta?.shortHash),
    committedAtIso: normalizeText(meta?.committedAtIso),
    commitCount: normalizeCommitCount(meta?.commitCount),
  };
  const payloadJson = JSON.stringify(payload, null, 2);

  return `// Auto-generated by scripts/stamp-build-meta.ts.
// Do not edit this file manually.

export type BuildMeta = {
  commitHash: string;
  shortHash: string;
  committedAtIso: string;
  commitCount: number;
};

export const BUILD_META: Readonly<BuildMeta> = Object.freeze(${payloadJson});

export function formatBuildLabel(meta: Partial<BuildMeta> = BUILD_META): string {
  const commitCount = normalizeCommitCount(meta?.commitCount);
  if (commitCount > 0) {
    return \`indev \${commitCount}\`;
  }
  const shortHash = normalizeLabelText(meta?.shortHash);
  if (shortHash) {
    return \`indev \${shortHash}\`;
  }
  return "indev";
}

function normalizeLabelText(value: unknown): string {
  if (typeof value !== "string") {
    return "";
  }
  return value.trim();
}

function normalizeCommitCount(value: unknown): number {
  const numeric = Number.parseInt(String(value ?? "").trim(), 10);
  if (!Number.isFinite(numeric) || numeric <= 0) {
    return 0;
  }
  return numeric;
}
`;
}

async function readTextFile(filePath: string): Promise<string> {
  try {
    return await readFile(filePath, "utf8");
  } catch {
    return "";
  }
}

function normalizeText(value: unknown): string {
  if (typeof value !== "string") {
    return "";
  }
  return value.trim();
}

function normalizeCommitCount(value: unknown): number {
  const numeric = Number.parseInt(String(value ?? "").trim(), 10);
  if (!Number.isFinite(numeric) || numeric <= 0) {
    return 0;
  }
  return numeric;
}
