// Auto-generated by scripts/stamp-build-meta.mjs.
// Do not edit this file manually.

export const BUILD_META = Object.freeze({
  "commitHash": "cd18ffd0ddcb2d89d8177d472f562767c5858176",
  "shortHash": "cd18ffd",
  "committedAtIso": "2026-04-12T21:29:41+02:00"
});

export function formatBuildLabel(meta = BUILD_META) {
  const shortHash = normalizeLabelText(meta?.shortHash);
  const timestamp = formatBuildTimestamp(meta?.committedAtIso);
  if (timestamp && shortHash) {
    return `Uppdaterad: ${timestamp} | ${shortHash}`;
  }
  if (timestamp) {
    return `Uppdaterad: ${timestamp}`;
  }
  if (shortHash) {
    return `Version: ${shortHash}`;
  }
  return "Version okand";
}

function formatBuildTimestamp(value) {
  const isoValue = normalizeLabelText(value);
  if (!isoValue) {
    return "";
  }
  const timestamp = new Date(isoValue);
  if (!Number.isFinite(timestamp.getTime())) {
    return "";
  }
  return [
    String(timestamp.getFullYear()).padStart(4, "0"),
    String(timestamp.getMonth() + 1).padStart(2, "0"),
    String(timestamp.getDate()).padStart(2, "0"),
  ].join("-") + " " + [
    String(timestamp.getHours()).padStart(2, "0"),
    String(timestamp.getMinutes()).padStart(2, "0"),
  ].join(":");
}

function normalizeLabelText(value) {
  if (typeof value !== "string") {
    return "";
  }
  return value.trim();
}
