// Auto-generated by scripts/stamp-build-meta.ts.
// Do not edit this file manually.

export type BuildMeta = {
  commitHash: string;
  shortHash: string;
  committedAtIso: string;
  commitCount: number;
};

export const BUILD_META: Readonly<BuildMeta> = Object.freeze({
  "commitHash": "596fc3475a364633e505a58c3378ae84af6ced46",
  "shortHash": "596fc34",
  "committedAtIso": "2026-04-14T11:23:41+02:00",
  "commitCount": 55
});

export function formatBuildLabel(meta: Partial<BuildMeta> = BUILD_META): string {
  const commitCount = normalizeCommitCount(meta?.commitCount);
  if (commitCount > 0) {
    return `indev ${commitCount}`;
  }
  const shortHash = normalizeLabelText(meta?.shortHash);
  if (shortHash) {
    return `indev ${shortHash}`;
  }
  return "indev";
}

function normalizeLabelText(value: unknown): string {
  if (typeof value !== "string") {
    return "";
  }
  return value.trim();
}

function normalizeCommitCount(value: unknown): number {
  const numeric = Number.parseInt(String(value ?? "").trim(), 10);
  if (!Number.isFinite(numeric) || numeric <= 0) {
    return 0;
  }
  return numeric;
}
