// Auto-generated by scripts/stamp-build-meta.ts.
// Do not edit this file manually.

export type BuildMeta = {
  commitHash: string;
  shortHash: string;
  committedAtIso: string;
  commitCount: number;
};

export const BUILD_META: Readonly<BuildMeta> = Object.freeze({
  "commitHash": "20a491d07a01c0099f89af99ffc9fc4e8c293641",
  "shortHash": "20a491d",
  "committedAtIso": "2026-04-13T15:20:11+02:00",
  "commitCount": 54
});

export function formatBuildLabel(meta: Partial<BuildMeta> = BUILD_META): string {
  const commitCount = normalizeCommitCount(meta?.commitCount);
  if (commitCount > 0) {
    return `indev ${commitCount}`;
  }
  const shortHash = normalizeLabelText(meta?.shortHash);
  if (shortHash) {
    return `indev ${shortHash}`;
  }
  return "indev";
}

function normalizeLabelText(value: unknown): string {
  if (typeof value !== "string") {
    return "";
  }
  return value.trim();
}

function normalizeCommitCount(value: unknown): number {
  const numeric = Number.parseInt(String(value ?? "").trim(), 10);
  if (!Number.isFinite(numeric) || numeric <= 0) {
    return 0;
  }
  return numeric;
}
